
const data_livingroom = {
    products: [
      {id:1,
        name: 'Jack Velvet couch',
        // slug: 'Jack Velvet couch In gold texture',
        category: ' Sofa Set',
        image: "/images/ls1.jpg", // 679px × 829 px
       price: 25000,
        countInStock: 7,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.5,
        numReviews: 10,
        description: 'A Comfortable couch in white texture',
      },
      {id:2,
        name: 'Eton 3 Seater  Sofa In Beige Colour',
        // slug: 'Eton 3 Seater  Sofa In Beige Colour',
        category: 'sofa',
        image: "/images/sofa1.jpg", // 679px × 829 px
        price: 25000, 
        countInStock: 12,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.4,
        numReviews: 10,
        description: 'cozy 3 seater sofa in beige colour',
      },
      {id:3,
        name: 'Orange Polyester double Seater Sofa ',
        // slug: 'Orange Polyester double Seater Sofa ',
        category: 'sofa',
        image: "/images/sofaset2.jpg", // 679px × 829 px
        price: 10000, 
        countInStock: 10,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.5,
        numReviews: 10,
        description: 'Stylish orange double seater sofa',
      },
      {id:4,
        name: 'Cosco Lounge seat In Pink Colour',
        // slug: 'Cosco Lounge seat In Pink Colour',
        category: 'Lounge seat',
        image: "/images/sofaset3.jpg", // 679px × 829 px
        price: 4000, 
        countInStock: 10,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.1,
        numReviews: 10,
        description: 'Comfy foam lounge seat ',
      },
      {id:5,
        name: 'Camden Fabric Sofa in greyish colour',
        // slug: 'Camden Fabric Sofa in greyish Colour',
        category: 'Sofa set',
        image: "/images/sofaset4.jpg", // 679px × 829 px
         price: 22500, 
        countInStock: 10,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.5,
        numReviews: 10,
        description: 'stylish greyish colour sofa set',
      },
      {id:6,
        name: 'premium gold shade sofa ',
        // slug: 'premium gold shade sofa ',
        category: 'premium sofaset',
        image: "/images/sofaset5.jpg", // 679px × 829 px
         price: 75000, 
        countInStock: 13,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.2,
        numReviews: 10,
        description: 'premium quality golden texture sofa set',
      },
      {id:7,
        name: 'velvet fabric single seater grey sofa',
        // slug: 'velvet fabric single seater grey sofa',
        category: 'sofa',
        image: "/images/sofaset6.jpg", // 679px × 829 px
       price: 12000, 
        countInStock: 5,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 3.9,
        numReviews: 10,
        description: ' Comfortable thick velvet fabric greyish colour sofa ',
      },
      {id:8,
        name: 'Lounge seat In bright orange Colour',
        // slug: 'Lounge seat In bright orange Colour',
        category: 'lounge seat',
        image: "/images/sofaset7.jpg", // 679px × 829 px
         price: 7000, 
        countInStock: 10,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.3,
        numReviews: 10,
        description: 'Asthetic Bright Orange Lounge seat ',
      },
      {id:9,
        name: 'One sided grey cushioned seat',
        // slug: 'One sided grey cushioned seat',
        category: 'sofa',
        image: "/images/sofaset8.jpg", // 679px × 829 px
        price: 12000, 
        countInStock: 10,
        /* brand: 'Lorem ipsum dolor sit amet1', */
        rating: 4.3,
        numReviews: 10,
        description: 'comfortable seating spot with one sided cushioned seat',
      },
      
      {id:10,
        name: 'Movable Lounge seat In white Colour',
        // slug: 'Movable Lounge seat In white Colour',
        category: 'Lounge seat',
        image: "/images/sofaset9.jpg",
        price: 10000,
        countInStock: 15,
        // brand: 'Lorem ipsum dolor sit amet2',
        rating: 4.0,
        numReviews: 10,
        description: 'Movable Lounge seat ',
      },
      {id:11,
        name: ' Lounge seat In Teal Colour',
        // slug: ' Lounge seat In Teal Colour',
        category: 'Lounge seat',
        image: "/images/sofaset10.jpg",
        price: 5000,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit ame3t',
        rating: 4.5,
        numReviews: 14,
        description: 'Stylish Lounge seat In Teal Colour',
      },
      {id:12,
        name: 'Single Sofa In Bright Yellow Colour',
        // slug: 'Single Sofa In Bright Yellow Colour',
        category:'sofa' ,
        image:"/images/sofaset11.jpg" ,
        price: 6500,
        countInStock: 5,
        // brand: 'Lorem ipsum dolor sit amet4',
        rating: 4.5,
        numReviews: 10,
        description: 'Single Sofa In Bright Yellow Colour',
      },
    ],
  };
  export default data_livingroom;