const products = [
      {
        id:13,
        name: 'Lucita Dining Set With White Marble',
        // slug: 'Lucita Dining Set With White Marble',
        category: 'diningtable',
        image: '/images/dining.jpg', // 679px × 829px
        price: 42550,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Lucita Solid Wood 6 Seater Dining Set With White Marble Top',
      },
      {
        id:14,
        name: 'Venice wood & Marble Dining Set',
        // slug: 'Venice wood & Marble Dining Set',
        category: 'diningtable',
        image: '/images/ld1.jpg', // 679px × 829px
        price: 13000,
        countInStock: 10,
        brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Venice Solid Wood & Marble top 4 Seater Dining Set',
      },
      {
        id:15,
        name: 'Lawson Wood 3 Seater Dining Set',
        // slug: 'Lawson Wood 3 Seater Dining Set',
        category: 'diningtable',
        image: '/images/dining1.jpg', // 679px × 829px
        price: 40820,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Lawson Wood 3 Seater Dining Set',
      },
      {
        id:16,
        name: 'Aoki Solid Wood 3 Seater Dining Set',
        // slug: 'Aoki Solid Wood 3 Seater Dining Set',
        category: 'diningtable',
        image: '/images/dining2.jpg', // 679px × 829px
        price: 10000,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Aoki Solid Wood 3 Seater Dining Set',
      },
      {
        id:17,
        name: 'Jin Solid Wood 4 Seater Dining Set ',
        // slug: 'Jin Solid Wood 4 Seater Dining Set ',
        category: 'diningtable',
        image: '/images/dining3.jpg', // 679px × 829px
        price: 20000,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Jin Solid Wood 4 Seater Dining Set ',
      },
      {
        id:18,
        name: 'Verduru 4 Seater Dining Set',
        // slug: 'Verduru 4 Seater Dining Set',
        category: 'diningtable',
        image: '/images/dining4.jpg', // 679px × 829px
        price: 22000,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Verduru 4 Seater Dining Set',
      },
      {
        id:19,
        name: 'Enigma Marble 4 Seater Dining Set',
        // slug: 'Enigma Marble 4 Seater Dining Set',
        category: 'diningtable',
        image: '/images/dining5.jpg', // 679px × 829px
        price: 22500,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Enigma Marble 4 Seater Dining Set',
      },
      {
        id:20,
        name: 'Zolva Glass Top 4 Seater Dining Set',
        // slug: 'Zolva Glass Top 4 Seater Dining Set',
        category: 'diningtable',
        image: '/images/dining6.jpg', // 679px × 829px
        price: 23890,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Zolva Glass Top 4 Seater Dining Set',
      },
      {
        id:21,
        name: 'Spaulding wooden 5 Seater Dining Set ',
        // slug: 'Spaulding wooden 5 Seater Dining Set ',
        category: 'diningtable',
        image: '/images/diningroom_table3.jpg',
        price: 50000,
        countInStock: 20,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.0,
        numReviews: 10,
        description: 'Spaulding wooden 5 Seater Dining Set ',
      },
      { 
        id:22,
        name: 'Sheesham Wood 6 Seater Dining Set',
        // slug: 'Sheesham Wood 6 Seater Dining Set',
        category: 'diningtable',
        image: '/images/dining8.jpg',
        price: 25000,
        countInStock: 20,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Princeton Sheesham Wood 4 Seater Dining Set',
      },
      {
        id:23,
        name: 'Hemming 4 Seater Dining Table ',
        // slug: 'Hemming 4 Seater Dining Table ',
        category: 'diningtable',
        image: '/images/dining9.jpg',
        price: 24600,
        countInStock: 15,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 14,
        description: 'Hemming 2 Seater Wall Mount Dining Table ',
      },
      {
        id:24,
        name: 'Venice Wood 4 Seater Dining Set',
        // slug: 'Venice Wood 4 Seater Dining Set',
        category: 'diningtable',
        image: '/images/diningroom_table4.jpg',
        price: 65000,
        countInStock: 5,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Venice Solid Wood & Marble top 4 Seater Dining Set',
      },
    ];

  export default products;