const  products = 
    [
      {id:71,
        name: 'Harper Wooden Queen Size Bed ',
        // slug: 'Lorem ipsum dolor sit 1',
        category: 'bed',
        image: '/images/c.jpg', // 679px × 829px
        price: 12210,
        countInStock: 10,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Harper Wooden Double Size, Queen Size Bed ',
      },
      {id:72,
        name: 'Solimo Ashburn King Bed',
        // slug: 'Lorem ipsum dolor sit 2',
        category: 'bed',
        image: '/images/beds2.jpg',
        price: 12500,
        countInStock: 20,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.0,
        numReviews: 10,
        description: 'Solimo Ashburn Engineered Wood King Bed',
      },
      {id:73,
        name: 'Solimo Medusa Queen Bed',
        // slug: 'Lorem ipsum dolor sit 3',
        category: 'bed',
        image: '/images/beds3.jpg',
        price: 11500,
        countInStock: 15,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 14,
        description: 'Solimo Medusa Engineered Wood Queen Bed with Box Storage ',
      },
      {id:74,
        name: ' Wenge Finish Queen Bed',
        // slug: 'aLorem ipsum dolor sit 4',
        category: 'bed',
        image:'/images/beds4.jpg',
        price: 12000,
        countInStock: 5,
        // brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: ' Solimo Aquilla Engineered Wood Wenge Finish Queen Bed',
      },
    ]
  ;
  export default products;